# Choose the version of dbt that will run the project.
# Supported versions are listed in https://fivetran.com/docs/transformations/dbt/setup-guide#prerequisites.
# If the version is not specified, dbt 0.18.0 will be used.
dbtVersion: 1.0.0

jobs:
# Give each job a unique name. The name will be displayed in the Fivetran dashboard once your jobs are imported.
# Job names must be unique.
 - name: every30minutestusk
   targetName: devtusk # The name of the target that will be used when running the job. If it's not specified, the target will be named 'prod'.
   schedule: '*/30 * * * *' # Define when this job should run, using cron format. This example will run every day at 12:00pm (according to your warehouse timezone). For help with cron formatting, visit https://crontab.guru/.
   steps:
     - name: run models tusk # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt run --vars '{"shopify_schema":"tusk_shopify"}' #dbt run # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     - name: test models tusk
       command: dbt test --vars '{"shopify_schema":"tusk_shopify"}' #This example will run all your tests.
 - name: every30minutesprive
   targetName: devprive # The name of the target that will be used when running the job. If it's not specified, the target will be named 'prod'.
   schedule: '*/30 * * * *' # Define when this job should run, using cron format. This example will run every day at 12:00pm (according to your warehouse timezone). For help with cron formatting, visit https://crontab.guru/.
   steps:
     - name: run models prive # Give each step in your job a name. This will enable you to track the steps in the logs.
       command: dbt run --vars '{"shopify_schema":"prive_shopify"}' #dbt run # Enter the dbt command that should run in this step. This example will run all your models. For a list of available commands visit https://docs.getdbt.com/reference/model-selection-syntax/.
     - name: test models prive
       command: dbt test --vars '{"shopify_schema":"prive_shopify"}' #This example will run all your tests.